### ISSUE TITLE
What is the difference between tuyasmart-ipc_sdk (this) and tuyasmart-ipcsdk?

### ISSUE THREAD

**Issue by tanshuai** [tuya/tuya-iotos-android-ipc-demo#8]
I found two **IPC SDK** from Tuya, this project used ```tuyasmart-ipc_sdk:1.2.2.12``` and [another](https://developer.tuya.com/en/docs/app-development/preparation?id=Ka8j28bt6i7eo)  used ```com.tuya.smart:tuyasmart-ipcsdk:3.27.5```. 

What is the difference between this and that? 

Thanks.

**Comment by Innocencellh** [comment]
Hello, thank you for your question.  In fact , this project used by  IPC device ,  another also used by IPC device , if you choose run with this project ,you should use tuyasmart-ipc_sdk:1.2.2.12 , but it's been a long time since  updated ,you can refer to this project  https://github.com/yuanye123/tuya-iotos-android-ipc-demo. If you run with another project , you should use another dependency .

**Comment by tanshuai** [comment]
> Hello, thank you for your question. In fact , this project used by IPC device , another also used by IPC device , if you choose run with this project ,you should use tuyasmart-ipc_sdk:1.2.2.12 , but it's been a long time since updated ,you can refer to this project https://github.com/yuanye123/tuya-iotos-android-ipc-demo. If you run with another project , you should use another dependency .

Thank you for your reply.
